import {
  expect,
  test,
} from "@playwright/test";

import { getPrisma } from "../../server/src/prisma.js";

const prisma = getPrisma();

test.describe(
  "Lab 2 Requester Ticket Flow",
  () => {
    let createdTicketNumber:
      | string
      | null = null;

    test.afterEach(async () => {
      if (!createdTicketNumber) {
        return;
      }

      /*
       * Test-only cleanup.
       *
       * This does NOT add a Delete Ticket
       * feature to the application.
       * It only removes the Ticket that
       * this E2E test created.
       */
      await prisma.ticket.deleteMany({
        where: {
          ticketNumber:
            createdTicketNumber,
        },
      });

      createdTicketNumber =
        null;
    });

    test(
      "Requester can select identity, create a ticket, find it, and open Ticket Detail",
      async ({ page }) => {
        await page.goto("/");

        await expect(
          page.getByRole(
            "heading",
            {
              name:
                /select development requester/i,
            }
          )
        ).toBeVisible();

        const requesterSelect =
          page.getByLabel(
            /development requester/i
          );

        await expect(
          requesterSelect
        ).toBeVisible();

        /*
         * Select the first active
         * Requester returned from DB.
         */
        const options =
          await requesterSelect
            .locator("option")
            .all();

        expect(
          options.length
        ).toBeGreaterThan(1);

        const firstRequesterValue =
          await options[1].getAttribute(
            "value"
          );

        expect(
          firstRequesterValue
        ).not.toBeNull();

        await requesterSelect.selectOption(
          firstRequesterValue!
        );

        await page
          .getByRole(
            "button",
            {
              name: /continue/i,
            }
          )
          .click();

        await expect(
          page.getByRole(
            "button",
            {
              name:
                /change requester/i,
            }
          )
        ).toBeVisible();

        /*
         * Open Create Ticket.
         */
        await page
          .getByRole(
            "button",
            {
              name:
                /create ticket/i,
            }
          )
          .click();

        await expect(
          page.getByRole(
            "heading",
            {
              name:
                /create ticket/i,
            }
          )
        ).toBeVisible();

        /*
         * Required read-only /
         * system-generated fields.
         */
        await expect(
          page.getByText(
            "Ticket Number",
            {
              exact: true,
            }
          )
        ).toBeVisible();

        await expect(
          page.getByText(
            "Ticket Date",
            {
              exact: true,
            }
          )
        ).toBeVisible();

        await expect(
          page.getByText(
            "Requester",
            {
              exact: true,
            }
          )
        ).toBeVisible();

        /*
         * Fill the form using
         * reference data from DB.
         */
        await page
          .getByLabel(
            /category/i
          )
          .selectOption({
            index: 1,
          });

        await page
          .getByLabel(
            /related system/i
          )
          .selectOption({
            index: 1,
          });

        await page
          .getByLabel(
            /requested priority/i
          )
          .selectOption(
            "MEDIUM"
          );

        const uniqueSummary =
          `E2E laptop issue ${Date.now()}`;

        await page
          .getByLabel(
            /ticket summary/i
          )
          .fill(
            uniqueSummary
          );

        await page
          .getByLabel(
            /description/i
          )
          .fill(
            "The laptop is running slowly and takes a long time to open applications."
          );

        /*
         * Submit the Ticket.
         */
        await page
          .getByRole(
            "button",
            {
              name:
                /submit ticket/i,
            }
          )
          .click();

        const successMessage =
          page.getByRole(
            "status"
          );

        await expect(
          successMessage
        ).toContainText(
          /ticket created successfully/i
        );

        /*
         * Read the official Ticket Number
         * generated by the backend.
         */
        const successText =
          await successMessage.innerText();

        const ticketNumberMatch =
          successText.match(
            /TKT-\d{4}-\d{6}/
          );

        expect(
          ticketNumberMatch
        ).not.toBeNull();

        const ticketNumber =
          ticketNumberMatch![0];

        /*
         * Store it so afterEach can
         * remove this test Ticket.
         */
        createdTicketNumber =
          ticketNumber;

        /*
         * Go to My Tickets.
         */
        await page
          .getByRole(
            "button",
            {
              name:
                /my tickets/i,
            }
          )
          .click();

        /*
         * There are desktop and mobile
         * representations in the DOM.
         * Use .first() so strict mode
         * does not fail on duplicates.
         */
        await expect(
          page
            .getByText(
              ticketNumber,
              {
                exact: true,
              }
            )
            .first()
        ).toBeVisible();

        await expect(
          page
            .getByText(
              uniqueSummary,
              {
                exact: true,
              }
            )
            .first()
        ).toBeVisible();

        /*
         * Open the desktop/tablet row.
         * The real browser applies
         * Bootstrap responsive styles.
         */
        const ticketRow =
          page
            .getByRole("row")
            .filter({
              hasText:
                ticketNumber,
            });

        await expect(
          ticketRow
        ).toBeVisible();

        await ticketRow
          .getByRole(
            "button",
            {
              name: /^open$/i,
            }
          )
          .click();

        /*
         * Confirm Ticket Detail.
         */
        await expect(
          page
            .getByText(
              ticketNumber,
              {
                exact: true,
              }
            )
            .first()
        ).toBeVisible();

        await expect(
          page
            .getByText(
              uniqueSummary,
              {
                exact: true,
              }
            )
            .first()
        ).toBeVisible();

        await expect(
          page.getByRole(
            "heading",
            {
              name:
                /attachments/i,
            }
          )
        ).toBeVisible();

        /*
         * The actual file input is hidden.
         * The visible control is its label.
         */
        await expect(
          page.getByText(
            "+ Add Attachment",
            {
              exact: true,
            }
          )
        ).toBeVisible();
      }
    );
  }
);